# Generated by Django 5.2.8 on 2026-01-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enroll_id', 'student__last_name', 'student__first_name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='uniq_enrollment_per_student_per_section'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'section'), name='uniq_student_name_in_section'),
        ),
    ]
